// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ignore: slash_for_doc_comments
/**
 * Default [FirebaseOptions] for use with your Firebase apps.
 *
 * Example:
 * ```dart
 * import 'firebase_options.dart';
 * // ...
 * await Firebase.initializeApp(
 *   options: DefaultFirebaseOptions.currentPlatform,
 * );
 * ```
 */
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWThhnWzEflVM7vGyjYoEiGBPINRaxks',
    appId: '1:512364087081:web:53f2ea1e1de22749165938',
    messagingSenderId: '512364087081',
    projectId: 'mitsuha-ba3d3',
    authDomain: 'mitsuha-ba3d3.firebaseapp.com',
    storageBucket: 'mitsuha-ba3d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnxE_I52z2bBck4ubBkAu1iKeHjDgaK_U',
    appId: '1:512364087081:android:78e56d47426b5ed3165938',
    messagingSenderId: '512364087081',
    projectId: 'mitsuha-ba3d3',
    storageBucket: 'mitsuha-ba3d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdd6zmqAl-Zn-XYoXcz3a0-b2L_CIFubA',
    appId: '1:512364087081:ios:d86ba4cbc77a1259165938',
    messagingSenderId: '512364087081',
    projectId: 'mitsuha-ba3d3',
    storageBucket: 'mitsuha-ba3d3.appspot.com',
    iosBundleId: 'com.example.wallapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdd6zmqAl-Zn-XYoXcz3a0-b2L_CIFubA',
    appId: '1:512364087081:ios:7564f2acee9ab24c165938',
    messagingSenderId: '512364087081',
    projectId: 'mitsuha-ba3d3',
    storageBucket: 'mitsuha-ba3d3.appspot.com',
    iosBundleId: 'com.example.wallapp.RunnerTests',
  );
}
